server:
  port: 8080
  #配置项目访问的根路径
  servlet:
    context-path: /fresh

#多数据源配置
spring:
  #数据源信息
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      druid:
        initial-size: 5 # 初始化大小
        min-idle: 5  #最小数量
        max-active: 20 #最大活跃数
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      datasource:
        master: #主数据源
          url: jdbc:mysql://localhost:3306/fresh?serverTimezone=UTC
          username: root
          password: xianleiming
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 指定datesource类型为Druid
          type: com.alibaba.druid.pool.DruidDataSource
        slave: # 从数据源
          url: jdbc:mysql://localhost:3306/fresh?serverTimezone=UTC
          username: root
          password: xianleiming
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 指定datesource类型为Druid
          type: com.alibaba.druid.pool.DruidDataSource

#    jpa:
#      show-sql: true  #查看执行操作的sql语句
#      database: mysql
#      # 通过实体类对数据库表结构的操作
#      hibernate:
#        ddl-auto: update
#
#    #  thymeleaf模板配置
#    thymeleaf:
#      prefix: classpath:/templates/
#      suffix: .html
#      cache: false
#      encoding: UTF-8
#      mode: HTML5
#
#
#
#

#MybatisPlus配置
mybatis-plus:
  #  mapper存放路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    驼峰命名  create_time  createTime
    map-underscore-to-camel-case: true
    # mapper的自动映射
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  别名
  type-aliases-package: com.example.demo_fresh.bean
  #  逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1  # 表示数据已经删除了
      logic-not-delete-value: 0 # 没有删除的时候值



